### ISSUE TITLE
Missing function: spds_exists

### ISSUE THREAD

**Issue by karpfen** [mapme-initiative/mapme.pipelines#3]
Hi @goergen95, I think there's a function definition missing for `spds_exists()`, used e.g. [here](https://github.com/mapme-initiative/mapme.pipelines/blob/main/src/002_get_wdpa.R#L25).
Can you please share the definition? I think it doesn't come from any of the loaded packages (at least I couldn't find it anywhere)

**Comment by goergen95** [comment]
Hi! This function should be available with `remotes::install_github("mapme-initiative/mapme.biodiversity", ref = "dev")`

**Comment by karpfen** [comment]
Ah, I must have forgotten to restart the session after installing it. Got it now, thanks!
