### ISSUE TITLE
Passing parameters to `write_portfolio`

### ISSUE THREAD

**Issue by karpfen** [mapme-initiative/mapme.pipelines#9]
The `mapme.biodiversity::write_portfolio` function accepts a `...` parameter for options to use when writing the gpkg file, but this is not used in this package:
https://github.com/mapme-initiative/mapme.pipelines/blob/31ec4f650b608d9e785252ae27a531c1ac5543e6/R/utils.R#L132

I'd like to pass e.g. `delete_layer = TRUE` to the function. Is it possible to do that? The only way to do this so far was to modify the package itself.
Is there any other way around this or could we introduce e.g. a config parameter for these options?

**Comment by goergen95** [comment]
Hm, we have the `overwrite` parameter that you can set in the global options which will delete already existing output files:

https://github.com/mapme-initiative/mapme.pipelines/blob/31ec4f650b608d9e785252ae27a531c1ac5543e6/R/run.R#L24-L25

I am hesitant to open these options to users of `mapme.pipelines`. We do call `sf::write_sf()` within `write_portfolio()`, but we do have some expectations to the underlying portfolio object which a casual user might not be aware of and which might lead confusions. Anyway, is your main reason for opening this issue accounted for with setting `overwrite: true` or do you have any other use case in mind?

**Comment by karpfen** [comment]
I think this issue is no longer relevant, since my initial problem was not caused by the package, but by the network filesystem that I attempted do write into. Thanks for the help, though!
